// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: onboarding/onboarding.proto

package onboarding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnboardingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	M             string                 `protobuf:"bytes,1,opt,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardingRequest) Reset() {
	*x = OnboardingRequest{}
	mi := &file_onboarding_onboarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardingRequest) ProtoMessage() {}

func (x *OnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_onboarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardingRequest.ProtoReflect.Descriptor instead.
func (*OnboardingRequest) Descriptor() ([]byte, []int) {
	return file_onboarding_onboarding_proto_rawDescGZIP(), []int{0}
}

func (x *OnboardingRequest) GetM() string {
	if x != nil {
		return x.M
	}
	return ""
}

type OnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardingResponse) Reset() {
	*x = OnboardingResponse{}
	mi := &file_onboarding_onboarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardingResponse) ProtoMessage() {}

func (x *OnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_onboarding_onboarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardingResponse.ProtoReflect.Descriptor instead.
func (*OnboardingResponse) Descriptor() ([]byte, []int) {
	return file_onboarding_onboarding_proto_rawDescGZIP(), []int{1}
}

func (x *OnboardingResponse) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

var File_onboarding_onboarding_proto protoreflect.FileDescriptor

const file_onboarding_onboarding_proto_rawDesc = "" +
	"\n" +
	"\x1bonboarding/onboarding.proto\x12\n" +
	"onboarding\"!\n" +
	"\x11OnboardingRequest\x12\f\n" +
	"\x01m\x18\x01 \x01(\tR\x01m\"\"\n" +
	"\x12OnboardingResponse\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a2^\n" +
	"\n" +
	"Onboarding\x12P\n" +
	"\x0fStartOnboarding\x12\x1d.onboarding.OnboardingRequest\x1a\x1e.onboarding.OnboardingResponseB Z\x1egobank/contracts/pb/onboardingb\x06proto3"

var (
	file_onboarding_onboarding_proto_rawDescOnce sync.Once
	file_onboarding_onboarding_proto_rawDescData []byte
)

func file_onboarding_onboarding_proto_rawDescGZIP() []byte {
	file_onboarding_onboarding_proto_rawDescOnce.Do(func() {
		file_onboarding_onboarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_onboarding_onboarding_proto_rawDesc), len(file_onboarding_onboarding_proto_rawDesc)))
	})
	return file_onboarding_onboarding_proto_rawDescData
}

var file_onboarding_onboarding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_onboarding_onboarding_proto_goTypes = []any{
	(*OnboardingRequest)(nil),  // 0: onboarding.OnboardingRequest
	(*OnboardingResponse)(nil), // 1: onboarding.OnboardingResponse
}
var file_onboarding_onboarding_proto_depIdxs = []int32{
	0, // 0: onboarding.Onboarding.StartOnboarding:input_type -> onboarding.OnboardingRequest
	1, // 1: onboarding.Onboarding.StartOnboarding:output_type -> onboarding.OnboardingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_onboarding_onboarding_proto_init() }
func file_onboarding_onboarding_proto_init() {
	if File_onboarding_onboarding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_onboarding_onboarding_proto_rawDesc), len(file_onboarding_onboarding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onboarding_onboarding_proto_goTypes,
		DependencyIndexes: file_onboarding_onboarding_proto_depIdxs,
		MessageInfos:      file_onboarding_onboarding_proto_msgTypes,
	}.Build()
	File_onboarding_onboarding_proto = out.File
	file_onboarding_onboarding_proto_goTypes = nil
	file_onboarding_onboarding_proto_depIdxs = nil
}
