#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE customer;
    CREATE DATABASE auth;
    CREATE DATABASE account;
    CREATE DATABASE kyc;
    GRANT ALL PRIVILEGES ON DATABASE customer TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE auth TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE account TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE kyc TO "$POSTGRES_USER";
EOSQL
