// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type OnboardingProcess struct {
	ID           int64
	OnboardingID uuid.UUID
	CustomerID   *uuid.UUID
	AccountID    *uuid.UUID
	Email        string
	Document     string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}
