// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: onboarding_processes.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createOnboardingProcess = `-- name: CreateOnboardingProcess :one
INSERT INTO onboarding_processes
    (onboarding_id, email, document, status)
values ($1, $2, $3, $4)
    RETURNING id, onboarding_id, customer_id, account_id, email, document, status, created_at, updated_at
`

type CreateOnboardingProcessParams struct {
	OnboardingID uuid.UUID
	Email        string
	Document     string
	Status       string
}

func (q *Queries) CreateOnboardingProcess(ctx context.Context, arg CreateOnboardingProcessParams) (OnboardingProcess, error) {
	row := q.db.QueryRow(ctx, createOnboardingProcess,
		arg.OnboardingID,
		arg.Email,
		arg.Document,
		arg.Status,
	)
	var i OnboardingProcess
	err := row.Scan(
		&i.ID,
		&i.OnboardingID,
		&i.CustomerID,
		&i.AccountID,
		&i.Email,
		&i.Document,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
