// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: kyc/kyc.proto

package kyc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKYCRequest) Reset() {
	*x = StartKYCRequest{}
	mi := &file_kyc_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKYCRequest) ProtoMessage() {}

func (x *StartKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKYCRequest.ProtoReflect.Descriptor instead.
func (*StartKYCRequest) Descriptor() ([]byte, []int) {
	return file_kyc_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *StartKYCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             string                 `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKYCResponse) Reset() {
	*x = StartKYCResponse{}
	mi := &file_kyc_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKYCResponse) ProtoMessage() {}

func (x *StartKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKYCResponse.ProtoReflect.Descriptor instead.
func (*StartKYCResponse) Descriptor() ([]byte, []int) {
	return file_kyc_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *StartKYCResponse) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_kyc_kyc_proto protoreflect.FileDescriptor

const file_kyc_kyc_proto_rawDesc = "" +
	"\n" +
	"\rkyc/kyc.proto\x12\x03kyc\"%\n" +
	"\x0fStartKYCRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\x10StartKYCResponse\x12\f\n" +
	"\x01b\x18\x01 \x01(\tR\x01b2>\n" +
	"\x03KYC\x127\n" +
	"\bStartKYC\x12\x14.kyc.StartKYCRequest\x1a\x15.kyc.StartKYCResponseB\x19Z\x17gobank/contracts/pb/kycb\x06proto3"

var (
	file_kyc_kyc_proto_rawDescOnce sync.Once
	file_kyc_kyc_proto_rawDescData []byte
)

func file_kyc_kyc_proto_rawDescGZIP() []byte {
	file_kyc_kyc_proto_rawDescOnce.Do(func() {
		file_kyc_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_kyc_proto_rawDesc), len(file_kyc_kyc_proto_rawDesc)))
	})
	return file_kyc_kyc_proto_rawDescData
}

var file_kyc_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kyc_kyc_proto_goTypes = []any{
	(*StartKYCRequest)(nil),  // 0: kyc.StartKYCRequest
	(*StartKYCResponse)(nil), // 1: kyc.StartKYCResponse
}
var file_kyc_kyc_proto_depIdxs = []int32{
	0, // 0: kyc.KYC.StartKYC:input_type -> kyc.StartKYCRequest
	1, // 1: kyc.KYC.StartKYC:output_type -> kyc.StartKYCResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kyc_kyc_proto_init() }
func file_kyc_kyc_proto_init() {
	if File_kyc_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_kyc_proto_rawDesc), len(file_kyc_kyc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyc_kyc_proto_goTypes,
		DependencyIndexes: file_kyc_kyc_proto_depIdxs,
		MessageInfos:      file_kyc_kyc_proto_msgTypes,
	}.Build()
	File_kyc_kyc_proto = out.File
	file_kyc_kyc_proto_goTypes = nil
	file_kyc_kyc_proto_depIdxs = nil
}
