// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: kyc/kyc.proto

package kyc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KYC_StartKYC_FullMethodName = "/kyc.KYC/StartKYC"
)

// KYCClient is the client API for KYC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KYCClient interface {
	StartKYC(ctx context.Context, in *StartKYCRequest, opts ...grpc.CallOption) (*StartKYCResponse, error)
}

type kYCClient struct {
	cc grpc.ClientConnInterface
}

func NewKYCClient(cc grpc.ClientConnInterface) KYCClient {
	return &kYCClient{cc}
}

func (c *kYCClient) StartKYC(ctx context.Context, in *StartKYCRequest, opts ...grpc.CallOption) (*StartKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartKYCResponse)
	err := c.cc.Invoke(ctx, KYC_StartKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KYCServer is the server API for KYC service.
// All implementations must embed UnimplementedKYCServer
// for forward compatibility.
type KYCServer interface {
	StartKYC(context.Context, *StartKYCRequest) (*StartKYCResponse, error)
	mustEmbedUnimplementedKYCServer()
}

// UnimplementedKYCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKYCServer struct{}

func (UnimplementedKYCServer) StartKYC(context.Context, *StartKYCRequest) (*StartKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartKYC not implemented")
}
func (UnimplementedKYCServer) mustEmbedUnimplementedKYCServer() {}
func (UnimplementedKYCServer) testEmbeddedByValue()             {}

// UnsafeKYCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KYCServer will
// result in compilation errors.
type UnsafeKYCServer interface {
	mustEmbedUnimplementedKYCServer()
}

func RegisterKYCServer(s grpc.ServiceRegistrar, srv KYCServer) {
	// If the following call panics, it indicates UnimplementedKYCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KYC_ServiceDesc, srv)
}

func _KYC_StartKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCServer).StartKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYC_StartKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCServer).StartKYC(ctx, req.(*StartKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KYC_ServiceDesc is the grpc.ServiceDesc for KYC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KYC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyc.KYC",
	HandlerType: (*KYCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartKYC",
			Handler:    _KYC_StartKYC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyc/kyc.proto",
}
