// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customer.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO customers (customer_id, name, email, document, type, status) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, customer_id, name, email, type, document, created_at, updated_at, status
`

type CreateParams struct {
	CustomerID uuid.UUID
	Name       string
	Email      string
	Document   string
	Type       string
	Status     string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Customer, error) {
	row := q.db.QueryRow(ctx, create,
		arg.CustomerID,
		arg.Name,
		arg.Email,
		arg.Document,
		arg.Type,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Email,
		&i.Type,
		&i.Document,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
