// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID         int64
	CustomerID uuid.UUID
	Name       string
	Email      string
	Type       string
	Document   string
	CreatedAt  time.Time
	UpdatedAt  *time.Time
	Status     string
}
